### ISSUE TITLE
Searching the surrogate

### ISSUE THREAD

**Issue by nachovfranco** [capaulson/pyKriging#12]
Hello!

I've been using pyKriging in my MSc project to manually optimise a design, but I haven't found any function to search the final trained surrogate for the location of a minimum. I have hacked together a new type of infill point in krige.py called "minimum" that uses the GA to search for a minimum.

Would you like me to issue a pull request on this?

Regards,
Ignacio Vidal

**Comment by capaulson** [comment]
Sure! Thanks for helping.
