### ISSUE TITLE
errors in simple kriging prediction attempt

### ISSUE THREAD

**Issue by florakarniav** [capaulson/pyKriging#13]
Hello, I am trying to perform a simple kriging prediction. My training data are of form:
X
2.0, 10.0
3.0, 10.0
5.0, 15.0
..
and 

Y
67.8
79.6
89.3
..

the simple code I run is the following:

```
k = kriging(X, y, testPoints=10)
k.train()
k_predictions = k.predict(X)
print k_predictions
```

I keep getting the following errors:
krige.py:85: RuntimeWarning: invalid value encountered in double_scalars
  X[i] = (X[i] - self.normRange[i][0]) / float(self.normRange[i][1] - self.normRange[i][0])
matrixops.py:46: RuntimeWarning: invalid value encountered in absolute
  self.LnDetPsi=2*np.sum(np.log(np.abs(np.diag(self.U))))
krige.py:85: RuntimeWarning: divide by zero encountered in true_divide
  X[i] = (X[i] - self.normRange[i][0]) / float(self.normRange[i][1] - self.normRange[i][0])

and naturally, k_predictions is nan. 

Can someone help or point me to the right direction?
Thank you in advance

**Comment by capaulson** [comment]
Strange. Are there any duplicate points in your data? 

Best, 
Chris

**Comment by capaulson** [comment]
I haven't seen any response to this come through. I'll close it for now, but feel free to reopen if you're still having issues with this.
