### ISSUE TITLE
linux muti process 

### ISSUE THREAD

**Issue by githubyong** [capaulson/pyKriging#14]
when i run 4 process krig.train and krig.predict under linux(redhat2.6.32, 32 CPU(s)),it is very slowl,it is 50 times slow than run it one by one.
and on windows it works well.

**Comment by capaulson** [comment]
Not sure here. This doesn't sound like a PyKriging issue. I've run large numbers of models on a 32 core machine before with no noticeable slowdown. This was using Ubuntu and AMD processors. The only thing I can think of, and can't really believe, is that you've filled the RAM on your 32 CPUs. 50x sounds about right for an IO limited process, but again, PyKriging shouldn't take that much ram. How many data points are in the models you're training?

**Comment by githubyong** [comment]
I was just run the demo which was given on the official site(http://www.pykriging.com/) whithout plot method,and my server has 64GB RAM,perhaps the problem is not about RAM.I think perhaps there is something wrong with train method about cpu.(I just open more than 4 terminal and run “python example.py”)

**Comment by capaulson** [comment]
This sounds like a non-pyKriging issue. Not sure if I can help. I'm going to close this for now, but if you find any evidence that pyKriging is locking threads or cores or something like that, please reopen. I can't replicate this one, so I can't debug it.
