### ISSUE TITLE
Get the meta model

### ISSUE THREAD

**Issue by LeoSbk** [capaulson/pyKriging#22]
Hi, it's not really an issue. I'm just wondering if is it possible to get the formula of the meta model (used in the predict function) ?
I didn't find any solution to my problem by my own so i'm calling for some help.

Thanks

**Comment by capaulson** [comment]
I'm not entirely sure what you're asking for. Can you provide more details about what you're trying to do?

**Comment by LeoSbk** [comment]
I'm trying to see how parameters can influence the result of a simulation, so i did many simulations with different parameters based on a an optimized LHS. Then I do a kriging of the problem in order to get the model of my simulator with "pyKriging.kriging(X,results)", i train it and then i can predict the result for a set of parameters, and its predicted error. But I'd like to extract the formula of the model to understand the influence of each parameter, more precisely the formula used to predict the result as a function of the parameters.

Something like that : result=f(x1,x2,..,xn)

Best,
Léo

**Comment by capaulson** [comment]
So, there isn't really a formula for the value at a given point, at least not in the f(x1,x2,..,xn) sense. It's a surrogate model, so the prediction at any one point in the model is an interpolation based on the previously observed points and a set of hyper-parameters that are trained such that the model closely fits the observed points. Wiki may be able to help understand how this type of model works: https://en.wikipedia.org/wiki/Kriging

The hyper-parameters do provide clues about the model's response, so those can be used to understand how the various dimensions of the model are behaving, but I don't think this is really what you're looking for.

**Comment by LeoSbk** [comment]
Thanks I better understand  how it works now, I'm gonna use the hyper-parameters to understand how my simulator behave.

Thanks for all,
And your toolbox is awesome and very useful btw

Léo
