### ISSUE TITLE
Project is Python 2 only without (obvious) notice of that fact

### ISSUE THREAD

**Issue by 1kastner** [capaulson/pyKriging#24]
I installed pyKriging via pip, i.e. the command "pip install pykriging" and all installations (some dependencies were resolved) were done successfully. Then I tried to validate the installation via the suggested command, i.e.:

    > python -c 'import pyKriging'
      File "<string>", line 1
        'import
              ^
    SyntaxError: EOL while scanning string literal

Sadly that did not work out. Then I slightly altered the command to

    >python -c "import pyKriging"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "E:\...\lib\site-packages\pyKriging\__init__.py", line 2, in <module>
        from .krige import *
      File "E:\...\lib\site-packages\pyKriging\krige.py", line 142
        except Exception, err:
                        ^
    SyntaxError: invalid syntax

That showed that the problem was related to that I was using Python 3 while the project uses Python 2. On this specific topic there is this helpful link: https://www.python.org/dev/peps/pep-3110/

So after having this debugging process, I thought it could be nice to be informed on the first page that this project is Python 2 only.  If it could be changed to be also compliant to Python 3, that would be great, too!

**Comment by 1kastner** [comment]
Or asking in another way: Would you accept a pull request for a version which is both Python 2 and Python 3 compliant (via e.g. six)?

**Comment by capaulson** [comment]
The Github is Python 2/3, need to push a new version to pip.

**Comment by 1kastner** [comment]
I'd be glad if it could happen soon :)
