### ISSUE TITLE
Documentation for your library

### ISSUE THREAD

**Issue by lenhhoxung86** [capaulson/pyKriging#33]
Hello,
It's not really an issue but I wonder what are the models used in your implementation.
Is there any where I can read the mathematical theory behind your models?
And what are the models supported by this library?

For example, I'm using the following code:
```
k = kriging(train_coors, train_z, name='simple')
k.train()
print('predicting...')
predicted_z = np.array([k.predict([row[0], row[1]]) for row in coordinates])
```
What is the mathematical behind? What options available for `name`?
The last question is: What's the difference between this lib and [PyKrige](https://pykrige.readthedocs.io/en/latest/api.html#krigging-algorithms)?
I've checked your website, but I couldn't find that information.

**Comment by capaulson** [comment]
Lot's of things to unpack here: 
1) The website has references that go into the math in-depth. I would recomend reviewing those. 
2) Name can be any string, just there to keep models clean. You can store these models with pickle, so it helps to have some information about what the model is, hench the name string. 
3) I guess two different libraries. pyKriging is geared towards a zero-config way of getting soultions. I can't speak for PyKrige.
