### ISSUE TITLE
How could I output the predicted array as a numpy array?

### ISSUE THREAD

**Issue by CR7zsc** [capaulson/pyKriging#36]
Hi, I'm sorry for bothering you. But I have a question for the predicted array.
I've trained a model, and then I want to output the result as a numpy array(because I want to save the array as a raster image by using gdal). Just like the kriging module in ArcGIS.  How could I?
Thanks very much.
@capaulson

**Comment by NiceSugar** [comment]
问题解决了吗？

**Comment by capaulson** [comment]
Any prediction is already returned as a numpy array. I'm not familiar with ArcGIS and can't help you match the format.
