### ISSUE TITLE
Regression Kriging not able to use the optimizer option when called from MATLAB

### ISSUE THREAD

**Issue by VarunPai** [capaulson/pyKriging#37]
I tried to call pyKriging from MATLAB. I used the following code in MATLAB to call pyKriging function.
```
krigObj = py.pyKriging.regressionkrige.regression_kriging(npxSamples,npySamples);
krigObj.train(pyargs('optimizer','ga')); #optimizer='pso' or 'ga'
```

The function is called successfully but I am getting the following error
```
エラー: regressionkrige>train (line 399)
Python エラー: UnboundLocalError: local variable 'final_pop' referenced before assignment
```
I understood that neither of the 'if' conditions gets executed and the 'final_pop' variable is empty. Hence I tried with default options assuming it should execute with 'pso'
`krigObj.train()`

It ran successfully without any error and I got the model.

I tried the same method with krige.py
```
krigObj = py.pyKriging.krige.kriging(npxSamples,npySamples);
krigObj.train(pyargs('optimizer','so'));
```
But this time I didn't get any error and the model was generated successfully. 

The difference; in regressionkrige.py  'is' is used to check the condition whereas in krige.py '==' is used. If there is a type mismatch even-if the value is same, the condition 'is' will return a False. 

Note : I executed directly from Python and I didn't get any error. I am using Python 3.5 version.

Could you replace the 'is' with '==' and update the code ?

**Comment by capaulson** [comment]
For Matlab I would use: https://optimizationcodes.wordpress.com/

Feel free to submit a PR for the Python stuff.
