### ISSUE TITLE
How the code works? What is sp, X, y and testfun?

### ISSUE THREAD

**Issue by Banano19** [capaulson/pyKriging#45]
Hi, I wanna know if you can help me figure out how this package works. I have the coordinates of each point where magnetometry data was taken but I need to know how to use it in the code. What is sp, X, y and testfun in the code?

**Comment by capaulson** [comment]
SP = sample plan, X is the vector that contains the observation vector, y contains observed data. Testfun is only used to plot the actual function over modeled data, and is only used in benchmarks. X and y is all you need to specify if you have already recorded data.
