### ISSUE TITLE
[Suggestion] Do you think this can be done using tensorflow?

### ISSUE THREAD

**Issue by pangard** [capaulson/pyKriging#6]
Just a suggestion: if you could write this code using google tensorflow (or maybe theano), it would be possible to make use of many processors, the gpu and in the near future, several machines. What do you think?

**Comment by capaulson** [comment]
I like the idea of parallel computing in general. I'm not sure if tensorflow is the right solution here, or if something like MPI is sufficient. The step that takes time is evaluating hyperparameters in a stochastic optimiser. It should be fairly easy enable parallel/clustering on that. In fact, I had it running at one point on a 32 core server in a parallel mode. What specific features do you think tensorflow brings to this toolkit?

**Comment by pangard** [comment]
I guess using tensorflow or theano is not convenient until any of those projects becomes more widespread, if they ever do. I would like to write code that uses all the cores/gpus/machines available using just one tool, rather that tensorflow or theano for evaluating the function and mpi for krigging, above all because they are nested.
Thanks anyone

**Comment by capaulson** [comment]
If you want to look into this further, take a look at where the  hyper parameter optimisation is done in the code. I use the Inspyred library for the multi-objective optimisation, which does have some built in parallelisation: http://pythonhosted.org/inspyred/reference.html?highlight=parallel#inspyred.ec.evaluators.parallel_evaluation_pp.

**Comment by pangard** [comment]
Thanks!

**Comment by capaulson** [comment]
I'm going to close this for now. Thanks for the feedback!
