### ISSUE TITLE
gradient enhanced kriging

### ISSUE THREAD

**Issue by achase90** [capaulson/pyKriging#9]
Hello! Pretty happy with the package so far. Any chance the gradient enhanced kriging from the textbook can get added to the package?
https://optimizationcodes.wordpress.com/

**Comment by capaulson** [comment]
I'll add it to the todo list. Co-kriging is still a work in progress, so I'll take on GE Kriging after that. Also, feel free to take it on. I would copy the basic Kriging class and make modifications. It should be fairly simple to port over.
